### ISSUE TITLE
fast5 file is not open.

### ISSUE THREAD

**Issue by bradabramson** [hyeshik/poreplex#14]
I'm getting this error (see below).  I used ont_fast5_api to demultiplex the multi-fast5s and then ran poreplex on those fast5s.  Any input would be helpful.  Thank you.

2019-01-31 14:21:01,777 Command line: /usr/local/projdata/8520/projects/PANGENOME/localenv/anaconda/envs/ONTIll/bin/poreplex -i ./demultiplex_fast5/ -o ./demultiplex_fast5/Poreplex --trim-adapter --barcoding --basecall --parallel 40 --live
2019-01-31 14:21:01,777 == Analysis settings ======================================
2019-01-31 14:21:01,777  * Input: ./demultiplex_fast5/ (live, 60 sec delay)
2019-01-31 14:21:01,777  * Output: ./demultiplex_fast5/Poreplex
2019-01-31 14:21:01,777  * Processes: 40
2019-01-31 14:21:01,777  * Presets: rna-r941.cfg
2019-01-31 14:21:01,777  * Basecall on-the-fly:  Yes (albacore 2.3.3)
2019-01-31 14:21:01,777  * Trim 3' adapter:      Yes
2019-01-31 14:21:01,777  * Filter concatenated read: No
2019-01-31 14:21:01,778  * Separate by barcode:  Yes
2019-01-31 14:21:01,778  * Real-time alignment:  No
2019-01-31 14:21:01,778  * FASTQ in output:      Yes
2019-01-31 14:21:01,778  * FAST5 in output:      No
2019-01-31 14:21:01,778  * Basecall table in output: No
2019-01-31 14:21:01,778 ===========================================================
2019-01-31 14:21:01,778
2019-01-31 14:24:21,105 [signal_analyzer.py:96] (37/cfe32c71-be0b-448f-bf2e-aa5099d51cfe.fast5) Unhandled exception OSError: Fast5 file is not open: ./demultiplex_fast5/37/cfe32c71-be0b-448f-bf2e-aa5099d51cfe.fast5
Traceback (most recent call last):
  File "/usr/local/projdata/8520/projects/PANGENOME/localenv/anaconda/envs/ONTIll/lib/python3.6/site-packages/poreplex/signal_analyzer.py", line 96, in process
    npread = prepare_loading(f5file)
  File "/usr/local/projdata/8520/projects/PANGENOME/localenv/anaconda/envs/ONTIll/lib/python3.6/site-packages/poreplex/signal_loader.py", line 79, in prepare_loading
    npread = NanoporeRead(filename, self.fast5prefix)
  File "/usr/local/projdata/8520/projects/PANGENOME/localenv/anaconda/envs/ONTIll/lib/python3.6/site-packages/poreplex/signal_loader.py", line 124, in __init__
    self.load()
  File "/usr/local/projdata/8520/projects/PANGENOME/localenv/anaconda/envs/ONTIll/lib/python3.6/site-packages/poreplex/signal_loader.py", line 205, in load
    self.channel_info = fast5.get_channel_info()
  File "/usr/local/projdata/8520/projects/PANGENOME/localenv/anaconda/envs/ONTIll/lib/python3.6/site-packages/ont_fast5_api/fast5_file.py", line 126, in get_channel_info
    self.assert_open()
  File "/usr/local/projdata/8520/projects/PANGENOME/localenv/anaconda/envs/ONTIll/lib/python3.6/site-packages/ont_fast5_api/fast5_file.py", line 57, in assert_open
    raise IOError("Fast5 file is not open: {}".format(self.filename))
OSError: Fast5 file is not open: ./demultiplex_fast5/37/cfe32c71-be0b-448f-bf2e-aa5099d51cfe.fast5

**Comment by hyeshik** [comment]
Hi @bradabramson,
Thank you very much for the reporting. I think this error could be fixed in the [newest release](https://github.com/hyeshik/poreplex/releases/tag/v0.4). Could you check if the problem persists in the latest build?

**Comment by bradabramson** [comment]
Hello, thank you for the quick reply.  I only just now tried it and I received this error from the python 3.6 version on the multi-fast5 and also the single-fast5 after I used “multi_to_single_fast5”.

##########################################################################
(LE=ONTIll)[babramso@bigmem-1:/usr/local/scratch/SYNBIO/babramson/RNA]$ poreplex -i /usr/local/scratch/SYNBIO/babramson/RNA/ -o /usr/local/scratch/SYNBIO/babramson/poreplex_V272/ --trim-adapter --barcoding --filter-chimera --basecall --parallel 40

Poreplex version 0.4 by Hyeshik Chang <hyeshik@snu.ac.kr>
- Cuts nanopore direct RNA sequencing data into bite-size pieces for RNA Biology

Output directory /usr/local/scratch/SYNBIO/babramson/poreplex_V272/ is not empty. Clear it? (y/N) y

== Analysis settings ======================================
* Input:       /usr/local/scratch/SYNBIO/babramson/RNA/
* Output:      /usr/local/scratch/SYNBIO/babramson/poreplex_V272/
* Processes:   40
* Presets:     rna-r941.cfg
* Basecall on-the-fly:         Yes (albacore 2.3.3)
* Trim 3' adapter:             Yes
* Filter concatenated read:    Yes
* Separate by barcode:         Yes
* Real-time alignment:         No
* FASTQ in output:             Yes
* FAST5 in output:             No
* Basecall table in output:    No
===========================================================

==> Processing FAST5 files
ERROR: [signal_analyzer.py:48] Unhandled exception FileNotFoundError: File b'/usr/local/projdata/8520/projects/PANGENOME/localenv/anaconda/envs/ONTIll/lib/python3.6/site-packages/poreplex/kmer_models/r9.4_180mv_70bps_5mer_RNA/template_median69pA.model' does not existTask exception was never retrieved
future: <Task finished coro=<ProcessingSession.run_process_batch() done, defined at /usr/local/projdata/8520/projects/PANGENOME/localenv/anaconda/envs/ONTIll/lib/python3.6/site-packages/poreplex/pipeline.py:183> exception=CancelledError()>
concurrent.futures._base.CancelledError

**Comment by hyeshik** [comment]
Hi @bradabramson,
There were some missing files from the binary package for v0.4.
I just release a new minor release v0.4.1 which should fix the problem.
Sorry for the inconvenience.

**Comment by bradabramson** [comment]
the kmer folder is not being installed when using pip repo (PYPI) but the git repo works.
