### ISSUE TITLE
signal_analyzer.py error

### ISSUE THREAD

**Issue by ernestopicardi** [hyeshik/poreplex#17]
Hi, 
I'm running poreplex in a linux machine using the following command:
poreplex -i /home3/Data/Nanopore/DIRECT_RNA/run_250319_Wt/fast5_pass/
 -o /home/epicardi/Nanopore/pass --trim-adapter --parallel 20 --align /home/epicardi/minimap2index/mm10.mmi --fastq

For each running process I'm getting:

2019-04-02 13:48:03,498 [signal_analyzer.py:114] (FAK29499_e03ca1e3175e68134af1625d2dc20000581e13e5_0.fast5#94610be8-25e4-4a12-980b-2376634ebfe7) Unha
ndled exception KeyError: "Can't open attribute (can't locate attribute: 'num_events_template')"
Traceback (most recent call last):
  File "/home/epicardi/bin/miniconda2/envs/py3/lib/python3.6/site-packages/poreplex/signal_analyzer.py", line 114, in process
    siganal.process()
  File "/home/epicardi/bin/miniconda2/envs/py3/lib/python3.6/site-packages/poreplex/signal_analyzer.py", line 259, in process
    events = self.load_events()
  File "/home/epicardi/bin/miniconda2/envs/py3/lib/python3.6/site-packages/poreplex/signal_analyzer.py", line 315, in load_events
    events = self.npread.load_fast5_events()
  File "/home/epicardi/bin/miniconda2/envs/py3/lib/python3.6/site-packages/poreplex/signal_loader.py", line 265, in load_fast5_events
    bcall = self.fast5.get_basecall()
  File "/home/epicardi/bin/miniconda2/envs/py3/lib/python3.6/site-packages/poreplex/fast5_file.py", line 142, in get_basecall
    summary['num_events'] = int(segattrs['num_events_template'])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/epicardi/bin/miniconda2/envs/py3/lib/python3.6/site-packages/h5py/_hl/attrs.py", line 60, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 77, in h5py.h5a.open
KeyError: "Can't open attribute (can't locate attribute: 'num_events_template')"

How can I fix this issue?

Many thanks,
Ernesto

**Comment by LucileSol** [comment]
Hi,
I am having the same problem with the same error message in the poreplex.log.

my command line is : 

poreplex -i/projects/annotation/adenovirus/poreplex/run3/fast5 -o /projects/annotation/adenovirus/poreplex/run3/output --trim-adapter

Thank you very much!

Lucile
