### ISSUE TITLE
Unhandled exception AttributeError: 'list' object has no attribute 'items'Task exception was never retrieved

### ISSUE THREAD

**Issue by ChaoTang-SCU** [hyeshik/poreplex#25]
2020-06-22 20:41:02,717 == Analysis settings ======================================
2020-06-22 20:41:02,717  * Input: /mnt/raid62/BetaCoV/RawData/20200620/20200620_0916_MN27328_FAM92901_ea10d670/fast5_pass/
2020-06-22 20:41:02,717  * Output: /mnt/raid62/BetaCoV/Person/tangchao/analysis/DrictRNA/Poreplex/output
2020-06-22 20:41:02,717  * Processes: 2
2020-06-22 20:41:02,717  * Presets: rna-r941.cfg
2020-06-22 20:41:02,717  * Basecall on-the-fly:  No (use previous analyses)
2020-06-22 20:41:02,717  * Trim 3' adapter:      Yes
2020-06-22 20:41:02,717  * Filter concatenated read: No
2020-06-22 20:41:02,717  * Separate by barcode:  Yes
2020-06-22 20:41:02,717  * Real-time alignment:  No
2020-06-22 20:41:02,717  * FASTQ in output:      Yes
2020-06-22 20:41:02,717  * FAST5 in output:      Yes
2020-06-22 20:41:02,717  * Basecall table in output: No
2020-06-22 20:41:02,717 ===========================================================
2020-06-22 20:41:02,717
2020-06-22 20:48:57,596 [signal_analyzer.py:48] Unhandled exception AttributeError: 'list' object has no attribute 'items'
2020-06-22 20:48:57,596 Traceback (most recent call last):
2020-06-22 20:48:57,596   File "/home/tangchao/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poreplex/signal_analyzer.py", line 48, in process_batch
2020-06-22 20:48:57,597     with SignalAnalyzer(config, batchid) as analyzer:
2020-06-22 20:48:57,597   File "/home/tangchao/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poreplex/signal_analyzer.py", line 72, in __init__
2020-06-22 20:48:57,597     WorkerPersistenceStorage(config).retrieve_objects(self)
2020-06-22 20:48:57,597   File "/home/tangchao/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poreplex/worker_persistence.py", line 48, in retrieve_objects
2020-06-22 20:48:57,597     storage = self.init_persistence_objects(self.config)
2020-06-22 20:48:57,597   File "/home/tangchao/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poreplex/worker_persistence.py", line 83, in init_persistence_objects
2020-06-22 20:48:57,597     storage['loader'] = SignalLoader(config['signal_processing'], config['inputdir'])
2020-06-22 20:48:57,597   File "/home/tangchao/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poreplex/signal_loader.py", line 41, in __init__
2020-06-22 20:48:57,597     self.scaler_model, self.scaler_cfg = self.load_scaler_model()
2020-06-22 20:48:57,597   File "/home/tangchao/.pyenv/versions/3.7.4/lib/python3.7/site-packages/poreplex/signal_loader.py", line 75, in load_scaler_model
2020-06-22 20:48:57,597     return keras.models.load_model(model_file), scaler_cfg
2020-06-22 20:48:57,597   File "/home/tangchao/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 180, in load_model
2020-06-22 20:48:57,597     return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
2020-06-22 20:48:57,597   File "/home/tangchao/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 178, in load_model_from_hdf5
2020-06-22 20:48:57,597     custom_objects=custom_objects)
2020-06-22 20:48:57,597   File "/home/tangchao/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
2020-06-22 20:48:57,597     return deserialize(config, custom_objects=custom_objects)
2020-06-22 20:48:57,597   File "/home/tangchao/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py", line 174, in deserialize
2020-06-22 20:48:57,598     printable_module_name='layer')
2020-06-22 20:48:57,598   File "/home/tangchao/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 338, in deserialize_keras_object
2020-06-22 20:48:57,598     config, module_objects, custom_objects, printable_module_name)
2020-06-22 20:48:57,598   File "/home/tangchao/.pyenv/versions/3.7.4/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 300, in class_and_config_for_serialized_keras_object
2020-06-22 20:48:57,598     for key, item in cls_config.items():
2020-06-22 20:48:57,598 AttributeError: 'list' object has no attribute 'items'
2020-06-22 20:48:58,899 Finished.

**Comment by dkoppstein** [comment]
This should be fixable by updating tensorflow to the latest nightly. [Here](https://github.com/tensorflow/tensorflow/pull/38339) is the fix in tensorflow.
